services:
  blockchain-analysis:
    container_name: blockchain-analysis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/blockchain-analysis